server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: password
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_app
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: false
    driver-class-name: org.mysql.Driver
  main:
    allow-circular-references: true

jira:
  app:
    jwtSecret: lamCustomSecretKeyForJiraAppABCDXYZBLABLABLA
    jwtExpirationMs: 86400000

springdoc:
  swagger-ui:
    path: swagger-ui.html
    operationsSorter: method

image:
  get:
    path: /api/file
