server:
  port: 8081

spring:
  security:
    user:
      name: superadmin@gmail.com
      password: password
      role: SUPER_ADMIN
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_app
    username: root
    password: 1234
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      globally_quoted_identifiers: true
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: false
    driver-class-name: org.mysql.Driver
  main:
    allow-circular-references: true

jira:
  app:
    jwtSecret: lamCustomSecretKeyForJiraAppABCDXYZBLABLABLA
    jwtExpirationMs: 86400000

springdoc:
  swagger-ui:
    path: swagger-ui.html
    operationsSorter: method

image:
  get:
    path: /api/v1/image
