server:
  port: 8081

spring:
  security:
    user:
      name: superadmin@gmail.com
      password: password
      role: SUPER_ADMIN
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_app
    username: root
    password: password
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      globally_quoted_identifiers: true
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: false
    driver-class-name: org.mysql.Driver
  main:
    allow-circular-references: true
  # QuocHao config email sender
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: nqlamjava@gmail.com
    password: f w x i g u b t y z s t r f o s
    test-connection: false
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  cache:
    type: redis
    redis:
      time-to-live: 40000
      cache-null-values: true

redis:
  host: localhost
  port: 6379

springdoc:
  swagger-ui:
    path: swagger-ui.html
    operationsSorter: method

image:
  get:
    path: /api/v1/image

